name: 'Download SCP:SL References'
description: 'Downloads managed DLLs used by SCP: Secret Laboratory'

inputs:
  branch:
    description: Steam branch
    required: false
    default: public
  directory:
    description: Where to place the DLLs
    required: false
    default: ${{ runner.temp }}/SCPSL-References
  specify-sl-references:
    description: Whether to set the SL_REFERENCES environment variable
    required: false
    default: "true"
  preset:  # TODO
    description: A preset of files to download. Accepted values are "essentials", "essentials-system", "advanced"
    required: false
  file-list:
    description: The file list to download. Ignored if the preset is specified.
    required: false
    default: "regex:SCPSL_Data/Managed/.+?\.dll"

outputs:
  target:
    description: The directory where references were placed
    value: ${{ steps.paths.outputs.target }}

runs:
  using: composite

  steps:
    - name: Install DepotDownloader
      uses: Axwabo/setup-steam-depot-downloader@v1.1
      with: 
        test: "false"

    - name: Resolve Paths
      id: paths
      run: |
        RAW_TEMP="${{ runner.temp }}"
        RAW_TARGET="${{ inputs.directory }}"
        TEMP="${RAW_TEMP//\\//}"
        TARGET="${RAW_TARGET//\\//}"
        REFERENCES=$TEMP/SCPSL-References

        echo "file-list=$TEMP/file-list.txt" >> "$GITHUB_OUTPUT"
        echo "references=$REFERENCES" >> "$GITHUB_OUTPUT"
        echo "managed=$REFERENCES/SCPSL_Data/Managed" >> "$GITHUB_OUTPUT"
        echo "target=$TARGET" >> "$GITHUB_OUTPUT"
      shell: bash

    - name: Specify File List
      if: inputs.preset == ''
      run: printf "${{ inputs.file-list }}" > ${{ steps.paths.outputs.file-list }}
      shell: bash

    - name: Download References
      run: DepotDownloader -app 996560 -branch ${{ inputs.branch }} -filelist ${{ steps.paths.outputs.file-list }} -dir ${{ steps.paths.outputs.references }}
      shell: bash

    - name: Create Target Directory
      run: mkdir -p ${{ steps.paths.outputs.target }}
      shell: bash

    - name: Move References
      run: mv ${{ steps.paths.outputs.managed }}/* ${{ steps.paths.outputs.target }}
      shell: bash

    - name: Specify SL_REFERENCES
      if: inputs.specify-sl-references != 'false'
      run: echo 'SL_REFERENCES=${{ steps.paths.outputs.target }}' >> "$GITHUB_ENV"
      shell: bash

branding:
  author: Axwabo
  color: black
  icon: download
